## CHANGE this to the name of your plugin.
name: EcoTech

## CHANGE this to your username.
author: Nycto

## CHANGE this to a meaninful but short description of your plugin.
description: A extensive farming addon that explores the vast possibility's of farming

## CHANGE this to the path of the class that extends JavaPlugin.
main: me.nycto.ecotech.EcoTech

## You can change this to link to your website or repository. You can also remove this line if you want to.
website: https://github.com/Nycto9648/EcoTech

## This value is automatically replaced by the version specified in your pom.xml file.
## Do not change this.
version: 1.0.0

## This is the minimum minecraft version required to run your plugin.
api-version: 1.14

## This is required and marks Slimefun as a plugin dependency.
depend:
- Slimefun